### ISSUE TITLE
Support environment without lxc-attach & lxc-ls

### ISSUE THREAD

**Issue by onixie** [montag451/lxc-tramp#3]
Thank you for such a great extension. 

I encountered some environments that only had `lxc` command available. Because `lxc-tramp` is using `lxc-attach` and `lxc-ls` internally, it is impossible to use under those environments. 

Is it possible to support `lxc` only environment? 
I had created a modified version that use `lxc` internally. 
Do you mind if I create a pull request for this?

**Comment by montag451** [comment]
Yes of course you can create a pull request. All contributions are welcome!

**Comment by moyamo** [comment]
Confusingly `lxc` commands  (without the hyphen) are actually interfacing with the lxd daemon rather than working with the containers directly (See https://discuss.linuxcontainers.org/t/comparing-lxd-vs-lxc/24). So it might be more appropriate to create a new tramp method lxd: for using these commands.

**Comment by montag451** [comment]
@moyamo Yes, you are right the best way to handle this issue is to create a new tramp method which would be called lxd:
@onixie I think you should create a new repository (called lxd-tramp for example :smiley:) and use the code of your pull request #4

**Comment by moyamo** [comment]
It doesn't seem necessary to create a whole new repository. Maybe I'll have time tonight to adapt 
onixie's pull request to have both working.

**Comment by montag451** [comment]
@moyamo It would be nice!

**Comment by onixie** [comment]
@moyamo Thank you for clearing the difference bwteen `lxc` and `lxc-xxx` commands and under which situation each set of commands will be used. 

@montag451 Sorry to overwrite on and remove the ability to use `lxc-xxx`. I didn't aware that `lxc` is optional in some linux distros. I will cancel my pull request first.

**Comment by moyamo** [comment]
@onixie wrote:
> If possible, I suggest to provide the two methods and let user to choose by setting certain customizable variable.

I don't think we should do this since some people might have some containers managed by lxd and others not.

**Comment by moyamo** [comment]
Too clarify, I think some people might have both containers managed by LXD and containers not managed by LXD.

**Comment by montag451** [comment]
I agree with @moyamo we should just provide two methods (lxc and lxd) and let the user choose between the two.

**Comment by onixie** [comment]
Hi, @montag451 

As you suggested, I created another repo and a new tramp method named `lxd` for LXD containers. 
So I will close this issue. 

Many thanks for your advice.
